name: Protect content from manual changes

on: 
  pull_request:
    paths:
    - 'content/**'

jobs:
  creator-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name:  Fail for non-Crowdin pushes
        if: github.actor != 'nodejs-crowdin' && github.actor != 'github-actions'
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Thank you for contribution!\n We are translating content with Crowdin and not doing manual updates with GitHub. Please check our guidelines in [i18n Contribution section](https://github.com/nodejs/i18n#contributing).\n\nPing @nodejs/i18n if you have any question'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
